name: Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
        node-version: 22.11.0

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/saucepan-did-mazaj:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/saucepan-did-mazaj:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/saucepan-did-mazaj:latest
            docker stop pan2 || true
            docker rm pan2 || true
            docker run -d -p 300:3003 --name pan2 ${{ secrets.DOCKER_USERNAME }}/saucepan-did-mazaj:latest
