name: Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod 666 /var/run/docker.sock
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/saucepan-did-mazaj:latest
            docker stop saucepan-did-mazaj || true
            docker rm saucepan-did-mazaj || true
            docker run -d --name saucepan-did-mazaj -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/saucepan-did-mazaj:latest
